# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_list_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
