# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_list_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='name',
        ),
    ]
